name: Build and Release

on:
  push:
    branches:
      - release
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:18-alpine  # Using a lightweight Node.js Alpine container

    steps:
      - name: Install dependencies
        run: |
          # Install dependencies and zip in Alpine
          apk add --no-cache git yarn zip

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install project dependencies
        run: yarn install

      - name: Build project
        run: yarn vite build -c vite.config.wp.ts

      - name: Zip artifacts
        run: |
          mkdir -p release
          zip -r release/wp_theme.zip wp/theme

      - name: "Upload wp/theme directory as artifact"
        uses: actions/upload-artifact@v3
        with:
          name: theme-artifact
          path: wp/theme
  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: |
            Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/wp_theme.zip
          asset_name: wp_theme.zip
          asset_content_type: application/zip
  sync_to_ftp:
    runs-on: ubuntu-latest
    needs: build  # Only run if the build job is successful

    container:
      image: node:16-alpine

    steps:
      - name: Install lftp
        run: apk add --no-cache lftp

      - name: Download wp/theme artifact
        uses: actions/download-artifact@v3
        with:
          name: theme-artifact

      - name: Sync to FTP server
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_PATH: ${{ secrets.FTP_REMOTE_PATH }}
        run: |
          lftp -c "
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER;
          mirror -R wp/theme $FTP_REMOTE_PATH --delete --only-newer;
          bye
          "
